timeout: 10m
severity: ["CRITICAL", "HIGH"]
ignore-unfixed: true
format: table
exit-code: 1
scanners:
  - vuln
  - secret
  - config
scan:
  skip-dirs:
    - node_modules
    - venv
    - .git
  skip-files:
    - "**/.env"
    - "**/*.tfstate"
secret:
  filters:
    - regexes:
        - '.*BEGIN (RSA|DSA|EC|PGP|OPENSSH) PRIVATE KEY.*'
        - '.*BEGIN PRIVATE KEY.*'
        - '.*BEGIN OPENSSH PRIVATE KEY.*'
        - 'AKIA[0-9A-Z]{16}'
        - '[a-z0-9]{32}' # AWS Secret Access Key
        - '[A-Za-z0-9/+=]{40}' # AWS Secret Access Key
        - '-----BEGIN CERTIFICATE-----'
        - 'ghp_[a-zA-Z0-9]{36}' # GitHub Personal Access Token
        - 'github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}' # GitHub Fine-grained PAT
        - '[a-zA-Z0-9]{2}:[a-zA-Z0-9]{32}:[a-zA-Z0-9]{8}' # AWS Secret Access Key
vulnerability:
  type:
    - os
    - library